
type ExecCommandCommandId = (
	// https://w3c.github.io/editing/docs/execCommand/
	| "backColor"
	| "bold"
	| "createLink"
	| "fontName"
	| "fontfontSize"
	| "foreColor"
	| "hiliteColor"
	| "italic"
	| "removeFormat"
	| "strikethrough"
	| "subscript"
	| "superscript"
	| "unerline"
	| "unlink"
	| "delete"
	| "formatBlock"
	| "forwardDelete"
	| "indent"
	| "insertHorizontalRule"
	| "insertHTML"
	| "insertImage"
	| "insertLineBreak"
	| "insertOrderedList"
	| "insertParagraph"
	| "insertText"
	| "insertUnorderedList"
	| "justifyCenter"
	| "justifyFull"
	| "justifyLeft"
	| "justifyRight"
	| "outdent"
	| "copy"
	| "cut"
	| "paste"
	| "defaultParagraphSeparator"
	| "redo"
	| "selectAll"
	| "styleWithCSS"
	| "undo"
	| "useCSS"

	// https://w3c.github.io/editing/docs/execCommand/#h-note
	| "decreaseFontSize"
	| "increaseFontSize"
	| "contentReadOnly"
	| "enableInlineTableEditing"
	| "enableObjectResizing"
	| "heading"
	| "insertBrOnReturn"
	| "readOnly"
	| "2D-Position"
	| "absolutePosition"
	| "clearAuthenticationCache"
	| "createBookmark"
	| "insertButton"
	| "insertFieldset"
	| "insertIframe"
	| "insertInput"
	| "insertMarquee"
	| "insertSelectDropdown"
	| "insertSelectListbox"
	| "insertTextarea"
	| "liveResize"
	| "multipleSelection"
	| "overwrite"
	| "print"
	| "refresh"
	| "saveAs"
	| "unbookmark"
	| "findString"
	| "fontSizeDelta"
	| "insertNewlineInQuotedContent"
	| "justifyNone"
	| "transpose"
	| "unselect"
);

interface Document {
	execCommand(commandId: ExecCommandCommandId, showUI?: boolean, value?: string): boolean;
}
